### ISSUE TITLE
AccessDenied exception when adding nori plugin to lambda from CustomResourceStack

### ISSUE THREAD

**Issue by ottlseo** [aws-samples/multi-modal-chatbot-with-advanced-rag#9]
### Problem
```
Received response status [FAILED] from custom resource. Message returned: Error
: An error occurred (AccessDeniedException) when calling the AssociatePackage o
peration: User: arn:aws:sts:::assumed-role/AdvancedRAG-CustomResour
ceStack-LambdaRole3A44B857-A7hVeQM1M3my/AdvancedRAG-CustomResourc-CustomResourc
eLambda42C1-UMoCMt1di8Cs is not authorized to perform: es:AssociatePackage on r
esource: arn:aws:es:us-west-2::domain/rag-hol-mydomain because no i
dentity-based policy allows the es:AssociatePackage action

Logs: /aws/lambda/AdvancedRAG-CustomResourc-CustomResourceLambda42C1-UMoCMt1di8
Cs

at invokeUserFunction (/var/task/framework.js:2:6)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async onEvent (/var/task/framework.js:1:369)
at async Runtime.handler (/var/task/cfn-response.js:1:1676) (RequestId: 0472957
c-42cc-4aa3-9bcd-024dd4931383)
```
### Solution

**Comment by ottlseo** [comment]
Fixed 
#10
